name: Swatch
version: "3.1.0"
panel_icon: "mdi:palette"
panel_title: Swatch
slug: swatch
description: Color detection in images to capture presense of known objects.
url: "https://github.com/NickM-27/swatch"
image: crzynik/swatch
startup: application
boot: auto
webui: "http://[HOST]:[PORT:4500]/"
ingress: true
ingress_port: 4500
ingress_entry: /
panel_admin: false
ports:
  4500/tcp: 4500
ports_description:
  4500/tcp: API
host_network: false
usb: false
tmpfs: true
full_access: false
environment:
  CONFIG_FILE: /config/swatch.yml
  DB_FILE: /media/swatch/swatch.db
  MEDIA_DIR: /media/swatch
options: {}
schema: {}
arch:
  - amd64
  - armv7
  - aarch64
map:
  - "media:rw"
  - "config:rw"
